.ALIASES
M_M1            M1(d=N00103 g=N00110 s=N00117 s=N00117 ) CN @PMOS.SCHEMATIC1(sch_1):INS28@BREAKOUT.MbreakP3.Normal(chips)
V_V1            V1(+=N00103 -=0 ) CN @PMOS.SCHEMATIC1(sch_1):INS55@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N00110 -=0 ) CN @PMOS.SCHEMATIC1(sch_1):INS71@SOURCE.VDC.Normal(chips)
V_V3            V3(+=N00117 -=0 ) CN @PMOS.SCHEMATIC1(sch_1):INS87@SOURCE.VDC.Normal(chips)
.ENDALIASES
