.ALIASES
M_M1            M1(d=N00177 g=N00188 s=N00195 s=N00195 ) CN @NMOS.SCHEMATIC1(sch_1):INS28@BREAKOUT.MbreakN3.Normal(chips)
V_V1            V1(+=N00177 -=0 ) CN @NMOS.SCHEMATIC1(sch_1):INS55@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N00188 -=0 ) CN @NMOS.SCHEMATIC1(sch_1):INS71@SOURCE.VDC.Normal(chips)
V_V3            V3(+=N00195 -=0 ) CN @NMOS.SCHEMATIC1(sch_1):INS87@SOURCE.VDC.Normal(chips)
.ENDALIASES
