.ALIASES
M_M1            M1(d=N00155 g=N00166 s=N00159 s=N00159 ) CN @CMOS.SCHEMATIC1(sch_1):INS28@BREAKOUT.MbreakP3.Normal(chips)
M_M2            M2(d=N00155 g=N00166 s=0 s=0 ) CN @CMOS.SCHEMATIC1(sch_1):INS57@BREAKOUT.MbreakN3.Normal(chips)
V_V1            V1(+=N00166 -=0 ) CN @CMOS.SCHEMATIC1(sch_1):INS84@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N00159 -=0 ) CN @CMOS.SCHEMATIC1(sch_1):INS100@SOURCE.VDC.Normal(chips)
.ENDALIASES
